# Generated by Django 4.2 on 2024-09-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
